image: maven:3.9.0-eclipse-temurin-19-focal

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - test
  - deploy

maven-build:
  stage: build
  script:
    - mvn -v
    - mvn package -DskipTests


run-tests:
  stage: test
  script:
  - mvn test

deploy-jar:
    stage: deploy
    script:
    - mvn install
