image: maven:3.9.0-eclipse-temurin-19-focal

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - test
  - deploy
  - pages

maven-build:
  stage: build
  script:
    - mvn -v
    - mvn compile

run-tests:
  stage: test
  script:
    - mvn jacoco:prepare-agent test jacoco:report verify

deploy-jar:
  stage: deploy
  script:
    - mvn install

jacoco-report:
  stage: pages
  script:
    - mkdir public
    - cp -r target/site/jacoco public/
  artifacts:
    paths:
      - public
  only:
    - master